name: Build UnFPK

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch: # يتيح لك تشغيل عملية البناء يدوياً متى شئت

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UnFPK-Windows
        # التقاط الملف التنفيذي سواء تم تصديره داخل مجلد Release أو في مجلد البناء الرئيسي
        path: |
          ${{github.workspace}}/build/Release/*.exe
          ${{github.workspace}}/build/*.exe
