name: Build UnFPK with CMake

on:
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure CMake
      # تم إضافة أمر التخطي هنا لحل مشكلة الإصدار القديم
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5

    - name: Build Project
      run: cmake --build build --config Release

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UnFPK-Ready
        path: build/**/*.exe
